name: aron_invoice
description: "Generuj Polskie faktury za darmo"
publish_to: 'none'
version: 1.0.2+3
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.8
  printing: ^5.12.0
  animated_text_kit: ^4.2.2
  google_fonts: ^6.2.1
  url_launcher: ^6.2.6
  cupertino_icons: ^1.0.6
  aron_flutter_utils:
    git:
      url: https://github.com/arononak/aron_flutter_utils.git
      ref: main
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/image.png